protected/controllers/IdeasController.php
<?php

class IdeasController extends Controller {

    public function actionIndex() {
        $this->render('index');
    }

    public function actionProxCursos() {

        $ipp = 16;

        $filtroCategoria = "";
        if (isset($_GET['cat'])) {
            $filtroCategoria = Yii::app()->request->getParam('cat');
        }
        $filtroBuscar = "";
        if (isset($_GET['buscar'])) {
            $filtroBuscar = Yii::app()->request->getParam('buscar');
        }
        $filtroOrden = "";
        if (isset($_GET['orden'])) {
            $filtroOrden = Yii::app()->request->getParam('orden');
        }

        $criteria = new CDbCriteria;
        $criteria->with = array(
            'idCathegory' => array('select' => 'na_cathegory'),
            'idLevel',
            'linkProposals'
        );

        if ($filtroCategoria != "") {
            $criteria->addCondition("idCathegory.na_cathegory LIKE '" . $filtroCategoria . "'");
        }

        if ($filtroBuscar != "") {
            $busqueda = new Searchh;
            if (!Yii::app()->user->isGuest) {
                $busqueda->id_user = Yii::app()->user->id;
            }
            $busqueda->text = $filtroBuscar;
            if ($busqueda->validate()) {
                $busqueda->save();
            }
            $criteria->addCondition("t.name LIKE '%" . $filtroBuscar . "%'");
        }

        $criteria->addCondition("t.active = 1");

        if ($filtroOrden != "") {
            if ($filtroOrden == "alfabetico") {
                $criteria->order = 't.name DESC';
            } else if ($filtroOrden == "dificultad") {
                $criteria->order = 't.id_level DESC';
            } else {
                $criteria->order = 't.create DESC';
            }
        } else {
            $criteria->order = 't.create DESC';
        }

        $listCat = Cathegory::model()->findAll();

        $list = Proposal::model()->findAll($criteria);
        
        $this->render('listado', array('categorias' => $listCat, 'list' => $list, 'categoria' => $filtroCategoria,'buscar'=>$filtroBuscar));
    }

    public function actionActivarPropuesta($id) {

        $proposal = Proposal::model()->findByPk($id);

        $proposal->active = 1;

        $proposal->update();

        $this->redirect(Yii::app()->urlManager->createUrl('ideas/listado', array('desactivo' => 1)));
    }

    public function actionDesactivarPropuesta($id) {
        $proposal = Proposal::model()->findByPk($id);

        $proposal->active = 0;

        $proposal->update();

        $this->redirect(Yii::app()->urlManager->createUrl('ideas/listado', array('desactivo' => 0)));
    }

    public function actionEditarPropuesta($id) {

        $proposal = Proposal::model()->findByPk($id);
        if (isset($_POST['Proposal'])) {

            $transaction = Yii::app()->db->beginTransaction();

            try {

                $proposal->attributes = $_POST['Proposal'];
                $proposal->id_cathegory = $_POST['id_cathegory'];
                $proposal->id_level = $_POST['id_level'];
                if (isset(Yii::app()->session['images_coverProposal'])) {
                    $proposal->deleteImages();
                    $proposal->cover = Yii::app()->session['images_coverProposal'];
                    $proposal->generateThumbnails();
                    unset(Yii::app()->session['images_coverProposal']);
                }

                $proposal->update();

                if (isset($_POST['tags'])) {
                    ProposalTag::model()->deleteAll('id_proposal=' . $proposal->id_proposal);
                    $tags = sprintf("%s", $_POST['tags']);  //Avoids XSS
                    $tagsArray = preg_split('/ |,/', $tags);
                    foreach ($tagsArray as $key => $value) {
                        $tag = Tag::model()->findByAttributes(array('tag' => $value));
                        if (!$tag) {
                            $tag = new Tag;
                            $tag->tag = $value;
                            $tag->save();
                        }
                        $ptag = ProposalTag::model()->findByAttributes(array('id_proposal' => $proposal->id_proposal, 'id_tag' => $tag->id_tag));
                        if (!$ptag) {
                            $ptag = new ProposalTag;
                            $ptag->id_proposal = $proposal->id_proposal;
                            $ptag->id_tag = $tag->id_tag;
                            $ptag->save();
                        }
                    }
                }

                $transaction->commit();
            } catch (Exception $e) {
                $transaction->rollback();
                Yii::log($e->getMessage(), CLogger::LEVEL_ERROR);
                //$this->redirect(Yii::app()->urlManager->createUrl('admin/editarCurso', array('id' => $course->id_course, 'msg' => 'Ocurrio un error al intentar guardar')));
            }
        }
        $tags = ProposalTag::model()->with('idTag')->findAllByAttributes(array(
            'id_proposal' => $id
        ));
        $listCat = Cathegory::model()->findAll();
        $listNiv = Level::model()->findAll();
        $this->render('editar', array('proposal' => $proposal, 'listCat' => $listCat, 'listNiv' => $listNiv, 'tags' => $tags));
    }

    public function actionUpload() {
        Yii::import("ext.EAjaxUpload.qqFileUploader");

        $folder = Yii::app()->params['coverProposalPath']; // folder for uploaded files
        $allowedExtensions = array("jpg", "jpeg", "png", "gif"); //array("jpg","jpeg","gif","exe","mov" and etc...
        $sizeLimit = 5 * 1024 * 1024; // maximum file size in bytes
        $uploader = new qqFileUploader($allowedExtensions, $sizeLimit);
        $result = $uploader->handleUpload($folder);
        $return = htmlspecialchars(json_encode($result), ENT_NOQUOTES);

        $fileSize = filesize($folder . $result['filename']); //GETTING FILE SIZE
        $fileName = $result['filename']; //GETTING FILE NAME

        Yii::app()->session['images_coverProposal'] = $fileName;

        echo $return; // it's array*/
    }

    public function actionListado($desactivo) {

        $criteria = new CDbCriteria;
        $criteria->with = array(
            'idCathegory' => array('select' => 'na_cathegory'),
            'idLevel',
            'ProposalTags' => array(
                'select' => 'id_ptag',
            ),
            'ProposalTags.idTag' => array(
                'select' => 'tag',
            ),
        );

        if ($desactivo == 1) {
            $criteria->addCondition("t.active = 1");
        } else {
            $criteria->addCondition("t.active = 0");
        }

        if (isset($_GET['dato'])) {
            $criteria->addCondition("t.name LIKE '%" . $_GET['dato'] . "%'");
        }

        $list1 = Proposal::model()->findAll($criteria);

        $this->render('propuestas', array('list1' => $list1));
    }

    public function actionPropuesta() {

        $proposal = new Proposal;

        if (isset($_POST['Proposal'])) {

            $proposal->attributes = $_POST['Proposal'];
            $proposal->id_cathegory = $_POST['id_cathegory'];
            $proposal->id_level = $_POST['id_level'];

            if (isset(Yii::app()->session['images_coverProposal'])) {
                $proposal->deleteImages();
                $proposal->cover = Yii::app()->session['images_coverProposal'];
                $proposal->generateThumbnails();
                unset(Yii::app()->session['images_coverProposal']);
            }

            $proposal->create = new CDbExpression('NOW()');
            $proposal->active = 1;
            if ($proposal->save(false)) {
                $this->redirect(Yii::app()->urlManager->createUrl('ideas/listado', array('desactivo' => 1)));
            }
        }

        $listCat = Cathegory::model()->findAll();
        $listNiv = Level::model()->findAll();
        $this->render('propuesta', array('proposal' => $proposal, 'listCat' => $listCat, 'listNiv' => $listNiv));
    }

    // Uncomment the following methods and override them if needed
    /*
      public function filters()
      {
      // return the filter configuration for this controller, e.g.:
      return array(
      'inlineFilterName',
      array(
      'class'=>'path.to.FilterClass',
      'propertyName'=>'propertyValue',
      ),
      );
      }

      public function actions()
      {
      // return external action classes, e.g.:
      return array(
      'action1'=>'path.to.ActionClass',
      'action2'=>array(
      'class'=>'path.to.AnotherActionClass',
      'propertyName'=>'propertyValue',
      ),
      );
      }
     */
}

protected/views/ideas/editar.php
<?php
Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/jquery.tagsinput.css', 'screen');
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/scholarships/jquery.tagsinput.min.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScript('taginput', "$(document).ready(function(){
			$('#tags').tagsInput({
			width: '100%',
			height: '45px',
			defaultText: ''
		});
	});"
        , CClientScript::POS_END);
?>

<div class="page-header">
    <h1>Editar Propuesta</h1>
    <p class="panel-title" style="font-size: 24px;">Completa el formulario para actualizar los datos de la propuesta. </p>
</div>

<div class="row">
    <div class="col-md-12">
        <a class="btn btn-default" href="<?php echo Yii::app()->urlManager->createUrl('admin/index') ?>">« Regresar al Administrador</a>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-8">

        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'register-form',
            'htmlOptions' => array(
                'class' => 'form-horizontal',
            )
        ));
        ?>

        <div class="form-group">
            <label class="col-lg-3" for="proposal_name">Nombre:</label>
            <div class="col-lg-7">
                <?php echo $form->textField($proposal, 'name', array('size' => '500', 'class' => 'form-control')); ?>
                <?php echo $form->error($proposal, 'name', array('style' => 'color: red;')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-3">¿Qué voy a aprender?:</label>
            <div class="col-lg-9">
                <?php echo $form->textarea($proposal, 'learn', array('rows' => '4', 'class' => 'form-control')); ?>
                <?php echo $form->error($proposal, 'learn', array('style' => 'color: red;')); ?>
            </div>
        </div>

        <div class="form-group">

            <label class="col-lg-3" for="user_email">Tags:</label>

            <div class="col-lg-9">

                <input class="form-control" id="tags" name="tags" value="<?php
                if (count($tags) > 0) {
                    foreach ($tags as $key => $value) {
                        echo $value->idTag->tag . ', ';
                    }
                }
                ?>" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-3" for="id_cathegory">Categoría</label>
            <div class="col-lg-9">
                <select class="combobox form-control" name="id_cathegory">
                    <option value>Seleccione una Categoría</option>
                    <?php foreach ($listCat as $cathegory) { ?>
                        <?php if ($proposal->id_cathegory == $cathegory->id_cathegory) { ?>
                            <option selected value="<?php echo $cathegory->id_cathegory; ?>"><?php echo $cathegory->na_cathegory; ?></option>
                        <?php } else { ?>
                            <option value="<?php echo $cathegory->id_cathegory; ?>"><?php echo $cathegory->na_cathegory; ?></option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>
        </div> 

        <div class="form-group">
            <label class="col-lg-3" for="id_cathegory">Nivel</label>
            <div class="col-lg-9">
                <select class="combobox form-control" name="id_level">
                    <option value>Seleccione un Nivel</option>
                    <?php foreach ($listNiv as $level) { ?>
                        <?php if ($proposal->id_level == $level->id_level) { ?>
                            <option selected value="<?php echo $level->id_level; ?>"><?php echo $level->na_level; ?></option>
                        <?php } else { ?>
                            <option value="<?php echo $level->id_level; ?>"><?php echo $level->na_level; ?></option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>
        </div> 

        <hr>

        <div class="form-group">
            <label class="col-lg-3" for="user_nickname">Cover:</label>
            <div class="col-lg-9">
                <?php
                $this->widget('ext.EAjaxUpload.EAjaxUpload', array(
                    'id' => 'uploadFile',
                    'config' => array(
                        'action' => Yii::app()->createUrl('ideas/upload'),
                        'allowedExtensions' => array("jpg", "jpeg", "png", "gif"), //array("jpg","jpeg","gif","exe","mov" and etc...
                        'debug' => false,
                        'sizeLimit' => 5 * 1024 * 1024, // maximum file size in bytes
                        'minSizeLimit' => 10 * 1024, // minimum file size in bytes
                        'onComplete' => "js:function(id, fileName, responseJSON){
				                        $('#picture img').attr('src','" . Yii::app()->request->baseUrl . "/images/coversProposals/'+fileName);
				                        $('#picture').css('display','block');
                                                        $('#picture p').text('');
				                   }",
                    )
                ));

                $imgPath = getcwd() . '/' . Yii::app()->params['coverProposalPath'];
                $mediumPath = $imgPath . substr($proposal->cover, 0, -4) . Proposal::COVER_MEDIUM_SUFFIX;
                $imagen = file_exists($mediumPath) ? $proposal->getCoverURL('small') : NULL;
                ?>
                <div id='picture' class='picture' style='display:block;float:left;'>
                    <?php if ($imagen) : ?>
                        <img style='width:35%; border-radius:5px;' src='<?php echo $imagen; ?>' />
                    <?php else: ?>
                        <img style='width:35%; border-radius:5px;'  />
                        <p>No se ha cargado una portada</p>
                    <?php endif; ?>
                </div>
            </div>						
        </div>				
        <hr>

        <input class="btn btn-warning btn-lg col-lg-offset-3" type="submit" value="Guardar">

        <?php $this->endWidget(); ?>
    </div>
    <div class="col-md-3">
        <?php
        if($proposal->active == 1){
            echo CHtml::link(
                'Desactivar esta propuesta', array('ideas/desactivarPropuesta', 'id' => $proposal->id_proposal), array('confirm' => '¿Estas completamente seguro de desactivar la propuesta?', 'class' => 'btn btn-danger', 'style' => 'background-color: #FF0000 !important')
        );
        }else{
            echo CHtml::link(
                'Activar esta propuesta', array('ideas/ActivarPropuesta', 'id' => $proposal->id_proposal), array('confirm' => '¿Estas completamente seguro de activar la propuesta?', 'class' => 'btn btn-danger', 'style' => 'background-color: #FF0000 !important')
        );
        }
        
        ?>
    </div>
</div>
<hr>

protected/views/ideas/index.php
<?php
/* @var $this IdeasController */

$this->breadcrumbs=array(
	'Ideas',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

protected/views/ideas/propuesta.php
<div class="page-header">
    <h1>Próximo curso</h1>
    <p class="panel-title" style="font-size: 24px;">Completa el formulario para ingresar una nueva propuesta. </p>
</div>

<div class="row">
    <div class="col-md-12">
        <a class="btn btn-default" href="<?php echo Yii::app()->urlManager->createUrl('admin/index') ?>">« Regresar al Administrador</a>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-12 page-layout">

        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'register-form',
            'htmlOptions' => array(
                'class' => 'form-horizontal',
            )
        ));
        ?>

        <div class="form-group">
            <label class="col-lg-3" for="proposal_name">Nombre:</label>
            <div class="col-lg-7">
                <?php echo $form->textField($proposal, 'name', array('size' => '500', 'class' => 'form-control')); ?>
                <?php echo $form->error($proposal, 'name', array('style' => 'color: red;')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-3">¿Qué voy a aprender?:</label>
            <div class="col-lg-9">
                <?php echo $form->textarea($proposal, 'learn', array('rows' => '4', 'class' => 'form-control')); ?>
                <?php echo $form->error($proposal, 'learn', array('style' => 'color: red;')); ?>
            </div>
        </div>


        <div class="form-group">
            <label class="col-lg-3" for="id_cathegory">Categoría</label>
            <div class="col-lg-9">
                <select class="combobox form-control" name="id_cathegory">
                    <option value>Seleccione una Categoría</option>
                    <?php foreach ($listCat as $cathegory) { ?>

                        <option value="<?php echo $cathegory->id_cathegory; ?>"><?php echo $cathegory->na_cathegory; ?></option>

                    <?php } ?>
                </select>
            </div>
        </div>  

        <div class="form-group">
            <label class="col-lg-3" for="id_cathegory">Nivel</label>
            <div class="col-lg-9">
                <select class="combobox form-control" name="id_level">
                    <option value>Seleccione un Nivel</option>
                    <?php foreach ($listNiv as $level) { ?>

                        <option value="<?php echo $level->id_level; ?>"><?php echo $level->na_level; ?></option>

                    <?php } ?>
                </select>
            </div>
        </div> 


        <hr>

        <div class="form-group">
            <label class="col-lg-3" for="user_nickname">Cover:</label>
            <div class="col-lg-7">
                <?php
                $this->widget('ext.EAjaxUpload.EAjaxUpload', array(
                    'id' => 'uploadFile',
                    'config' => array(
                        'action' => Yii::app()->createUrl('ideas/upload'),
                        'allowedExtensions' => array("jpg", "jpeg", "png", "gif"), //array("jpg","jpeg","gif","exe","mov" and etc...
                        'debug' => false,
                        'sizeLimit' => 5 * 1024 * 1024, // maximum file size in bytes
                        'minSizeLimit' => 10 * 1024, // minimum file size in bytes
                        'onComplete' => "js:function(id, fileName, responseJSON){						                        
				                        $('#picture img').attr('src','" . Yii::app()->request->baseUrl . "/images/coversProposals/'+fileName);
				                        $('#picture').css('display','block');
				                   }",
                    )
                ));
                ?>
                <div id='picture' class='picture' style='display:none;float:left;margin-left:20px;'>
                    <img style='width:200px;height:200px' />
                </div>
            </div>						
        </div>	

        <input class="btn btn-warning btn-lg col-lg-offset-3" type="submit" value="Guardar">

<?php $this->endWidget(); ?>
    </div>
</div>
<hr>

protected/views/ideas/propuestas.php
<div class="page-header">
    <h1>Listado de Propuestas</h1>
    <p class="panel-title" style="font-size: 24px;">Listado de próximos cursos.</p>
</div>

<div class="row">
    <div class="col-md-12">
        <form class="form-inline" style="margin-left: 5px;">
            <div class="form-group col-xs-4">
                <input class="form-control " id="exampleInputEmail2" placeholder="Nombre de la propuesta" name="dato" value="<?php
                if (isset($dato)) {
                    echo $dato;
                }
                ?>">
            </div>
            <button type="submit" class="btn btn-default" style="margin-left: -20px;">Buscar</button>
        </form>

        <hr>

        <div style="text-align: center;">
            <a class="btn btn-success" href="<?php echo Yii::app()->urlManager->createUrl('ideas/propuesta'); ?>">Nueva Propuesta</a>
        </div>
        <h2 style="text-align: center;">Propuestas (<?php echo count($list1) ?>)</h2>
        <table class="table table-bordered" style="margin: 2px 0 20px 20px; width: 98%">
            <thead>
                <tr>
                    <th>Categoría</th>
                    <th>Propuesta</th>
                    <th>Contenido</th>
                    <th>Nivel</th>
                    <th>Creación</th>
                    <th style="width: 14%;">Opción</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($list1 as $proposal) { ?>
                    <?php
                    $tags = "";
                    foreach ($proposal->ProposalTags as $tag) {
                        $tags = $tags.", ".$tag->idTag->tag;
                    }
                    ?>
                    <tr>
                        <td>
                            <?php if ($proposal->id_cathegory != null) { ?>
                                <button type="button" class="btn btn-default tags" data-toggle="tooltip" data-placement="top" title="<?php echo trim($tags,",");?>"><?php
                                            echo $proposal->idCathegory->na_cathegory;
                                            ?>
                                </button>
                            <?php } ?>

                        </td>

                        <td><?php echo $proposal->name; ?></td>
                        <td><?php echo $proposal->learn; ?></td>
                        <td>
                            <?php
                            if ($proposal->id_level != null) {

                                echo $proposal->idLevel->na_level;
                            }
                            ?>
                        </td>
                        <td>
                            <?php echo substr($proposal->create, 0, 10); ?>
                        </td>
                        <td>
                            <a type="button" class="btn btn-warning btn-xs" href="<?php echo Yii::app()->urlManager->createUrl('ideas/editarPropuesta', array('id'=>$proposal->id_proposal)); ?>">Editar</a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

    </div>

    <script type="text/javascript">
        $('.tags').tooltip();
    </script>